name: Publish to DockerHub

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "clounsbury1"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: clounsbury1/tools-container:latest

      - name: Test the container
        uses: ./
        with:
          image: 'clounsbury1/toolscontainer:latest'
          command: 'az version && pwsh -c \$psversiontable && packer version && terraform version && func version'